//! Generated gateway bootstrap for sdkwork-notary.
//! Regenerated by pnpm gateway:assembly:materialize.

use axum::Router;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub fn assemble_application_router() -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_notary_app_api::gateway_mount(service));
    router = router.merge(sdkwork_routes_notary_backend_api::gateway_mount(service));
    router = router.merge(sdkwork_routes_notary_http_auth::gateway_mount());
    ApplicationAssembly { router }
}
